### ISSUE TITLE
Allow ordering of rows and columns of each Heatmap in a HeatmapList

### ISSUE THREAD

**Issue by doliv071** [jokergoo/ComplexHeatmap#115]
I would like to be able to re-order each Heatmap in a HeatmapList. This is useful when you want to plot heatmaps side-by-side but they are not identical samples.

Maybe this is already possible, but I haven't been able to get around ordering all heatmaps identical to the primary heatmap.

Thanks,
-Dave

**Comment by jokergoo** [comment]
The row order of all heatmaps are all the same that the row order is determined by the "main heatmap":

```
Heatmap(m1, row_order = ..., cluster_rows = FALSE) + Heatmap(m2) + ...
```

 or by:

```
draw(ht_list, row_order = ...)
```

The column order of each heatmap is independent, you need to control it manually:

```
Heatmap(m1, column_order = ..., cluster_columns = FALSE) +
Heatmap(m2, column_order = ..., cluster_columns = FALSE)
```

If you mean the heatmaps have same set of samples but not identical (let's say the first heatmap has the full set of samples), you can adjust the column order from the second heatmap by:

```
hc = hclust(dist(t(m1)))
column_order = colnames(m1)[hc$order]
Heatmap(m1, cluster_order = column_order, cluster_columns = FALSE) +
Heatmap(m2, cluster_order = intersect(column_order, colnames(m2)), cluster_columns = FALSE)
```

**Comment by doliv071** [comment]
Thanks for the quick response. I guess I'll just swap columns and rows in order to allow independent clustering. I'm assuming that the reason the rows cannot be independently clustered is that there is no way to add the dendrogram to each heatmap in the heatmapList, is this correct?

**Comment by jokergoo** [comment]
No, basically you cannot make independent heatmaps by rows. One advantage of the ComplexHeatmap package is to make multiple heatmaps where same rows always correspond to same objects so that you can associate multiple information for same objects in the heatmaps. In that case, since row orders are all the same for all heatmaps, if there is clustering on rows for the "main heatmap", all heatmaps share the same clustering, thus there is no need to plot all row dendrograms for all heatmaps.

If you really want to make heatmaps independently clustered, actually, you can just put heatmaps in a layout of `1 x n` where you can do as follows:

```{r}
pushViewport(viewport(x = 0, width = 0.5, just = "left"))
m1 = matrix(rnorm(100), 10)
draw(Heatmap(m1), newpage = FALSE)
popViewport()

pushViewport(viewport(x = 1, width = 0.5, just = "right"))
m2 = matrix(rnorm(100), 10)
draw(Heatmap(m2), newpage = FALSE)
popViewport()
```

**Comment by doliv071** [comment]
Excellent that is exactly what I was looking for. 

Thanks for your help.
