### ISSUE TITLE
heatmap_legend_side

### ISSUE THREAD

**Issue by up201007037** [jokergoo/ComplexHeatmap#15]
Everytime I try to use heatmap_legend_xxx I always get the same error:

Error in Heatmap(mat, name = "relAbund", col = palete, heatmap_legend_title = "x") :
  unused argument (heatmap_legend_title = "x")

Can someone check that?
Thank's!

**Comment by jokergoo** [comment]
I think it is because you are using the new version but still using the old syntax. The settings for legend have been changes in latest versions. Now all parameters related to heatmap legend are controled by `heatmap_legend_param`. By using `heatmap_legend_param`, you can customize the legend more flexibly than before.

E.g. if you want to change the title:

```{r}
Heatmap(..., heatmap_legend_param = list(title = ...))
```

There is a new vignette on how to customize the legend: (http://bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s5.legend.html)

**Comment by up201007037** [comment]
Thank's a lot for the reply. I am using the version 1.0.0 from bioconductor. 
Still got the same error:

Error in Heatmap(mat, col = palete, heatmap_legend_param = list(title = "x")) : 
  unused argument (heatmap_legend_param = list(title = "x"))

it only recognizes heatmap_legend_size and nothing more.

**Comment by up201007037** [comment]
I am sorry, I installed the new version. It's working. Thank's a lot! (the bioconductor doesn't have the last version, you need to download the tar.gz)

**Comment by jokergoo** [comment]
Yes, you are right. It is always not easy to install BIoconductor pacakges in devel branch : )
