### ISSUE TITLE
Add row_order to plotDataFrame

### ISSUE THREAD

**Issue by schelhorn** [jokergoo/ComplexHeatmap#18]
Awesome to see the development of this package making such great strides. I have another feature request, though. Would it be possible to get row_order and column_order parameters for plotDataFrame?

**Comment by jokergoo** [comment]
Sorry for the late reply. I only added `row_order` parameter to `plotDataFrame()` function because it can be shared by all heatmaps while column order can only be applied to a single heatmap.

And also I would suggest to manually split the data frame into several matrix and construct each one by `Heatmap()` and finally concatenate them. `plotDataFrame()` is quite limited and not full functional.
