### ISSUE TITLE
Is there a way to use text annotations instead of colors ?

### ISSUE THREAD

**Issue by sahilseth** [jokergoo/ComplexHeatmap#22]
What would be the best way to use text annotations in the bottom of oncoprint?

Thanks!

**Comment by jokergoo** [comment]
First chunk of code is only to generate demonstration data.

```{r}
mat = read.table(paste0(system.file("extdata", package = "ComplexHeatmap"), 
	"/tcga_lung_adenocarcinoma_provisional_ras_raf_mek_jnk_signalling.txt"), 
	header = TRUE,stringsAsFactors=FALSE, sep = "\t")
mat[is.na(mat)] = ""
rownames(mat) = mat[, 1]
mat = mat[, -1]
mat=  mat[, -ncol(mat)]
mat = t(as.matrix(mat))
mat = mat[, 1:20]

alter_fun_list = list(
	background = function(x, y, w, h) {
		grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "#CCCCCC", col = NA))
	},
	HOMDEL = function(x, y, w, h) {
		grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "blue", col = NA))
	},
	AMP = function(x, y, w, h) {
		grid.rect(x, y, w-unit(0.5, "mm"), h-unit(0.5, "mm"), gp = gpar(fill = "red", col = NA))
	},
	MUT = function(x, y, w, h) {
		grid.rect(x, y, w-unit(0.5, "mm"), h*0.33, gp = gpar(fill = "#008000", col = NA))
	}
)

col = c("MUT" = "#008000", "AMP" = "red", "HOMDEL" = "blue")
```

Now let's start from here. To add a text annotation, you need to do following settings:
1. position of text
2. rotation of text
3. height of the annotation viewport

In following code, `offset = 1` means position of text is on the top of the corresponding annotation viewport; `rot = 90` is the rotation of the text and `just = "right'` is how text is aligned to it position

The height of the text annotation is calculated by `max_text_width` (because text is rotated) and 
it is set in `annotation_height` by `unit.c` if there are other annotation graphics.

```{r}
ha = HeatmapAnnotation(
	sth = sample(c("a", "b"), 20, replace = TRUE),
	text = anno_text(sample(month.name, 20, replace = TRUE), offset = 1, rot = 90, just = 'right'),
	annotation_height = unit.c(unit(5, "mm"), max_text_width(month.name))
)
```

Finally send `ha` to `bottom_annotation` argument:

```{r}
oncoPrint(mat, get_type = function(x) strsplit(x, ";")[[1]],
	alter_fun_list = alter_fun_list, col = col, 
	bottom_annotation = ha, 
	heatmap_legend_param = list(title = "Alternations", at = c("AMP", "HOMDEL", "MUT"), 
		labels = c("Amplification", "Deep deletion", "Mutation")))
```

![test](https://cloud.githubusercontent.com/assets/449218/11197220/45e7161e-8cbc-11e5-9eb4-946a729ba83b.png)

**Comment by sahilseth** [comment]
Awesome! It looks better now, but I am getting the following error:

```
Error in `[.unit.list`(anno_size, seq_len(i)) : 
  index out of bounds (unit list subsetting)
```

**Comment by sahilseth** [comment]
Also, is there a way to add a label in the bottom annotation bar. If one has multiple annotations using the same color scheme, it becomes confusing.

Again, thanks a lot for this package!

**Comment by sahilseth** [comment]
Got it! need a unit for each annotation, in a specific order:

- First for text
- Followed by one of each color bar

```
clin_cols = list(
	gender = c(Male = "white", Female = "black"),
	smoking_type = c(NEVER = "white", FORMER = "grey", CURRENT = "black")
)
ann_hts = rep(unit(5, "mm"), length(clin_cols))
ba =  dplyr::select(sampinfo, one_of(names(clin_cols))) %>% 
	HeatmapAnnotation(col = clin_cols, 
	                     text = column_anno_text(sampinfo$sample_id, rot = 90, offset = 1, just = 'right'),
	                     annotation_height = unit.c(max_text_width(sampinfo$sample_id), ann_hts))

```

Where, `clin_cols` is a list colors for each annotation.

**Comment by jokergoo** [comment]
Yes, you are right. Colors for the annotations are controled by `col` argument by a list of named color vectors.

Regards to the annotation label, you can use `decorate_annotation()` function. E.g. add a label on the left:

After you make the heatmap:

```{r}
decorate_annotation("sth", {
    grid.text("sth", x = unit(-2. "mm"), just = "right")
})
```

`sth` is the name of the annotation, the second `sth` in `grid.text()` is the label you want to add. Since the label is on the left of the annotation area, here we set x to `unit(-2, "mm")` to put the label on the left and set `just` to `right` to make the label align to its right.

**Comment by sahilseth** [comment]
Great this works well, thanks!
