### ISSUE TITLE
Is it possible to draw a vertical HeatmapList?

### ISSUE THREAD

**Issue by johanneskoester** [jokergoo/ComplexHeatmap#24]
As the question says, it would be great to be able to draw vertical lists of heatmaps.
Is there any workaround that would allow this with the current version? If not, is it a planned feature?

Thanks!
Johannes

**Comment by jokergoo** [comment]
Hi, thanks for the comment. Currently adding heatmap vertically is not supported yet, but actually you can do it by defining a list of column annotations. I am not sure whether I should support it in the future versions because it will increase the complexity of the package a lot. And also to my opinion, most people prefer to arrange heatmaps horizontally.

**Comment by johanneskoester** [comment]
Thanks! Btw., great package!
