### ISSUE TITLE
Can we scale data and trim data for better presentation

### ISSUE THREAD

**Issue by lileok** [jokergoo/ComplexHeatmap#26]
Hi jokergoo,

In the Heatmap, can we scale data and/or trim data AFTER the clusters defined in the original data?
Since in some cases, if we input a scaled data, the cluster pattern may be different from the one using original data. Some  options like below or some alternatives I can try would be great.
```
scale: "row" "column" "none" 
trim: Logic
trim_size: numeric
```

Thanks for the package.

**Comment by jokergoo** [comment]
Hi, I just realize it has already one and half month since you raised this issue. So sorry for the very late reply.

The package does not provide scaling on the matrix because you can do it before making the heatmap.
The package only focuses on visualization on the data while not preprocessing.

However, to solve your problem, you can separate scaling and making the dendrogram by first generating the dendrogram and then doing the scaling. When making the heatmap, the dendrogram can be passed to the heatmap, something like:

```{r}
dend = as.dendrogram(hclust(dist(mat)))
scaled_mat = t(scale(t(mat)))
Heatmap(scaled_mat, cluster_rows = dend)
```

**Comment by lileok** [comment]
Thanks for your reply and solution. Trimming data or scaling data are also for better data visualization. 

Thanks and best.
