### ISSUE TITLE
pass ggplot2 objects in HeatmapAnnotation()

### ISSUE THREAD

**Issue by RudRho** [jokergoo/ComplexHeatmap#261]
Hi Gu,

Just wondering is it possible to pass ggplot into the HeatmapAnnotation()? This could be a great expansion of many features on the annotations. Like a density plot in rowAnnotation colored by wether samples with mutation or not.

Understand this is asking too much. But any response is greatly appreciated.

Cheers,
MJ

**Comment by jokergoo** [comment]
Theoretically yes, but I haven't tried so far. See following example:

```r
library(ggplot2)
g = ggplot(mpg, aes(displ, hwy, colour = class)) + geom_point()

m = matrix(rnorm(100), 10)
Heatmap(m, top_annotation = HeatmapAnnotation(ggplot = anno_empty(height = unit(6, "cm"))))

decorate_annotation("ggplot", {
	vp = current.viewport()$name
	print(g, vp = vp)
})
```
![screenshot from 2019-02-27 09-16-15](https://user-images.githubusercontent.com/449218/53475585-96aa4480-3a70-11e9-8983-9cc01377aed2.png)

Because you can draw the ggplot2 object in a certain viewport and each heatmap annotation contains a viewport that users can access, but you need to make sure the graphic elements in ggplot2 plots are properly aligned to the heatmap rows or columns.

**Comment by RudRho** [comment]
This is greaaat!

I will try seeing if the alignment works. I will keep you updated. 

Cheers
MJ
