### ISSUE TITLE
Different output from draw() and pdf()

### ISSUE THREAD

**Issue by m3lorra** [jokergoo/ComplexHeatmap#336]
Hi, 

I've been getting different results from when I plot the heatmap to see it with draw() and then when I save it. 

This is what I've been doing and the outputs: 

```
lsk_hp=Heatmap(lsk.mat.log2tpm_scaled, 
    name='Z-score',
    clustering_distance_rows = "euclidean",
    clustering_method_rows = "ward.D2",
    clustering_distance_columns = "euclidean",
    clustering_method_columns = "ward.D2",
    row_km = 5,
    column_split = 2,
    width=unit(8, 'cm'),
    height = unit(15, "cm"),
    row_title = c("1", "2", "3", "4", '5'),
    row_title_rot = 0,
    col = colorRamp2(lsk.myBreaks, lsk.myCol),
    show_column_names=FALSE,
    show_row_names=FALSE,
    row_dend_reorder=TRUE,
    column_dend_reorder=TRUE,
    top_annotation=lsk.colAnn)
draw(lsk_hp, heatmap_legend_side = "right", annotation_legend_side = "left")
```
![Screen Shot 2019-07-03 at 13 03 15](https://user-images.githubusercontent.com/28356418/60590096-028c1900-9d93-11e9-8b78-ac095583e288.png)

But then when I save exactly the same plot: 

```
pdf("heatmap_LSK.pdf", width=10, height=15)
draw(lsk_hp, heatmap_legend_side = "right", annotation_legend_side = "left")
dev.off()

```
I get this output, where the clustering is different and also I get a grey line in the fifth cluster: 
![Screen Shot 2019-07-03 at 13 04 34](https://user-images.githubusercontent.com/28356418/60590129-20597e00-9d93-11e9-8e9e-e0fa7b90ac49.png)

Using draw I always get the same result but when I save it is most of the times different. I wonder if I'm doing this wrong or there is a bug. 

Thank you,
Steph

**Comment by jokergoo** [comment]
It is because you set k-means clustering on rows. Every time when you run `draw(lsk_hp, ...)`, the k-means clustering will be re-executed and the results might be different. To keep the heatmaps the same, you can

1. set seed

```r
set.seed(123)
draw(...)
```

Or assign the object returned from `draw()`:

```r
lsk_hp2 = draw(lsk_hp, ...)
# all identical
draw(lsk_hp2)
draw(lsk_hp2)
draw(lsk_hp2)
```

Here `lsk_hp` only contains data and parameters for the clustering while the clusterings are not executed yet. After calling `draw()`, heatmap is drawn and clustering is performed, and here `lsk_hp2`  contains all the results for clustering and heatmap, and reruning `draw()` on `lsk_hp2` will not rerun clustering any more.

**Comment by m3lorra** [comment]
Got it
Thank you!
