### ISSUE TITLE
Space between annotation and plot

### ISSUE THREAD

**Issue by heyuan7676** [jokergoo/ComplexHeatmap#380]
Hi!

I'm trying to use `rowAnnotation(link = row_anno_link(at = genes_idx,  labels = labels, padding = 0.5)` to produce the plot as shown in [http://bioconductor.riken.jp/packages/3.8/bioc/vignettes/ComplexHeatmap/inst/doc/s4.heatmap_annotation.html](url)  section "Mark some of the rows/columns". 

Since I have thousands of rows, I'd like the annotation to touch the rows, instead of leaving a wide gap between the lines and the rows. Could you let me know how I can do this?

Thank you!

**Comment by jokergoo** [comment]
If the `anno_mark()` annotation (please use `anno_mark()` instead of `anno_link()` in version >= 2.0.0) is used as added to the heatmap by `+`, e.g.:

```r
Heatmap(...) + rowAnnotation(mark = anno_mark(...))
```

Then you can control the space between heatmap and row annotation by:

```r

m = matrix(1:1000, byrow = TRUE, nr = 100)
anno = anno_mark(at = c(1:4, 20, 60, 97:100), labels = month.name[1:10], which = "row")
ht_list = Heatmap(m) + rowAnnotation(mark = anno)
draw(ht_list, ht_gap = unit(0, "mm"))
```

![image](https://user-images.githubusercontent.com/449218/67150718-a9051700-f2bb-11e9-9078-389a88102289.png)

If you have two heatmaps and one row anntation, similarly you can:

```r
ht_list = Heatmap(...) + Heatmap(...) + rowAnnotation(...)
draw(ht_list, ht_gap = unit(c(5, 0), "mm'))
```

**Comment by heyuan7676** [comment]
Gotcha! Thanks!
