### ISSUE TITLE
Heatmap Title and Column Title?

### ISSUE THREAD

**Issue by emccarthy23** [jokergoo/ComplexHeatmap#401]
Is it possible to have both a heatmap title and column title (or conversely two column titles one on the bottom and one on the top)? The use case I am thinking of is to have a column title on the bottom designating a title for the columns plus a title on top for the entire heatmap (e.g. title on the bottom "Clusters", title on the top "CD14-CD16+ monocytes")?

**Comment by jokergoo** [comment]
For a heatmap, you only have one title, but since a heatmap is a list of one heatmap, there can also be a title for the heatmap list, see the following example:

```r
m = matrix(rnorm(100), 10)

ht = Heatmap(m, column_title = "title1", column_title_side = "bottom") + NULL
draw(ht, column_title = "title2", column_title_side = "top")
```

Note here `+ NULL` is important to convert a single heatmap to a list of heatmap.

![image](https://user-images.githubusercontent.com/449218/70380317-69f95680-1939-11ea-923b-7c0f54257863.png)

**Comment by jokergoo** [comment]
aha, the position of "title 1" and "title 2" are not well aligned. If you want to use it in the paper, you need to manually adjusted in Illustrator or Inkscape.
