### ISSUE TITLE
Duplicate anno row name

### ISSUE THREAD

**Issue by helenhuangmath** [jokergoo/ComplexHeatmap#403]
Hi,

Thank you for developing ComplexHeatmap! 

I have a question about duplicated row name annotation on heatmap. I have several ChIP peaks mapping to one gene, and I want to point two or more peaks to one gene. So far I could use ComplexHeatmap to show duplicated gene name. Is there any way that I could avoid duplicated names and pointing several peaks to one gene? 
Thank you so much for your help!

My current plot from ComplexHeatmap:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/43098514/69361663-ec57fa00-0c5a-11ea-939c-0f65f9c70aaf.png">

I want to plot like this (from a published paper):
<img width="469" alt="image" src="https://user-images.githubusercontent.com/43098514/69362268-3097ca00-0c5c-11ea-8749-127a8a55e496.png">

**Comment by jokergoo** [comment]
Hi, I don't think the plot from the paper is a good visualization. In the plot, Casp3 has 2-3 peaks, Ccr6 has one peak, that is OK, but what if a gene has a lot of peaks, say 100. When a gene has multiple peaks, why don't you just average them and take the mean across peaks? I would guess, the multiple peaks that are annotated to a same gene should have similar pattern and you don't need to list all individual peaks.

If you insist, you can still use `anno_mark()` but set the font size to a very small value (so that lines relate to a same gene will be clustered together). Later you add the gene names by hand with Illustrator or photoshop.
