### ISSUE TITLE
option to flip rows and cols for axes ? 

### ISSUE THREAD

**Issue by akhst7** [jokergoo/ComplexHeatmap#437]
Any easy option to assign rows to X and cols to Y axis (without transpose an entire df)  ?

**Comment by jokergoo** [comment]
What do you mean by "X" and "Y"? The dimension of the heatmap? That is a transposition. Why don't you want to transpose your matrix?

**Comment by akhst7** [comment]
I have a fairly large data (in data.table) with a few dozen columns of demographic parameters which make it complicate to transpose the table.  Typically, the first column has a list of subject ID and columns have vectors of demographic as well as relevant numerical data.  I usually   subset the data by these demographic parameters (e.g  Heatmap(DT[V1==foo]) but the problem is that heatmaps in publications historically have subject IDs in the column and variables in the row.  That's why I asked if it was possible to easily interchange col and row assignment in the ComplexHeatmap.

**Comment by jokergoo** [comment]
Then why don't you first temporarily convert the data table into a matrix then transpose the matrix for the heatmap? ComplexHeatmap can not transpose the heatmap directly.

**Comment by akhst7** [comment]
That's what I do at the moment but as mentioned above, I have to create so many of transposed data.table individually created by subsetting based on demographic variables. Also  Unlike DF, data.table does not have rowname, which makes it more difficult to transpose.  If complexheatmap can simply implement rotating axes, it will be a lot easier for me.

**Comment by stanstrup** [comment]
I came here to ask for the same thing. When working on your plot it would be very convenient to quickly see the transposed version. As mentioned above transposing is not just a single function call when you are working with tibbles or data.tables. and you need parameters to things like left_annotation, row_split, clustering_distance_rows, etc.

**Comment by jokergoo** [comment]
OK, sounds reasonable. I will try to add a `t()` method on the `Heatmap()` object.

**Comment by jokergoo** [comment]
Most of the parts in the heatmap can be easily transposed but not everything. E.g. the annotations cannot be transposed because the x-y coordinate internally is already hard coded, which means a column annotation cannot be converted to a row annotation.

@akhst7 for the rownames issue, actually you can set the argument `row_labels`. This is an alternative for row names.

On the other hand, the input for `Heatmap()` is normally a matrix, so if your input is a tibble/data.table, you should better to convert it to a matrix.

Following is an example with tibble as input:

```
> tb = tibble(a = 1:10, b = 10:1)
> Heatmap(tb, row_labels = letters[1:10])
Warning message:
The input is a data frame, convert it to a matrix.
```

![image](https://user-images.githubusercontent.com/449218/140904178-68102bf8-571a-4f96-b687-7400f877c51d.png)
