### ISSUE TITLE
How to write an cell_fun outside Heatmap()?

### ISSUE THREAD

**Issue by lileok** [jokergoo/ComplexHeatmap#50]
Hi Zuguang,

I would like to write a cell_fun for daily use, for example, plotting some number in corresponding heatmap cell (correlation heatmap with correlation value plotted).

`cell_function = f(){
          some code
}`

Then feed the `cell_function` to `Heatmap()`

`Heatmap(mat, cell_fun = cell_function)`

Thanks ,

**Comment by jokergoo** [comment]
You can define as:

```{r}
cell_function =  function(j, i, x, y, width, height, fill) {
    # the function body
}
```

The pre-defined arguments are:

- `j`: column index in the matrix. Column index corresponds to the x-direction in the viewport, that's why `j` is put as the first argument.
- `i`: row index in the matrix.
- `x`: x coordinate of middle point of the cell which is measured in the viewport of the heatmap body.
- `y`: y coordinate of middle point of the cell which is measured in the viewport of the heatmap body.
- `width`: width of the cell.
- `height`: height of the cell.
- `fill`: color of the cell.

You can find examples of `cell_fun` here:

http://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/s2.single_heatmap.html#toc_6

**Comment by lileok** [comment]
Thanks for the information.
