### ISSUE TITLE
Specific colors assigned to specific values of contact matrix

### ISSUE THREAD

**Issue by rcalandrelli** [jokergoo/ComplexHeatmap#551]
Hello,

I am plotting a contact matrix with values from ``0`` to ``N`` using a white-to-red gradient colorbar generated using ``colorRamp2``. Also, I am plotting some specific entries of the contact matrix in blue by setting those specific values to ``NA``, and then using the parameter ``na_col="blue"`` when I make the heatmap. 

In addition, I would like to plot also other two groups of entries with two different colors. To do so, my idea was to make the first group of entries equal to ``-1``, the second equal to ``-2``, and then assign two specific colors (for example green and yellow) to those two values when plotting, but I could not find a way to do so. If it is not possible to assign a color to each specific value, maybe it could be possible to assign a color based on a lower- or an upper-cutoff, this would allow at least for other two custom colors besides the ``NA`` values.

Is there any way to implement these ideas, or any other way to accomplish this task?

Thank you in advance for your help,
Riccardo

**Comment by jokergoo** [comment]
Hi, the `col` argument accepts a color mapping function which takes values in and generate the corresponding colors while how to define the mapping is completely user-defined. As what `colorRamp2()` does, it generates a function which linearly maps values to colors. For your case, I would think the way to generate this color mapping function is:

```r
col_fun1 = colorRamp2(c(0, 10), c("white", "red")) # assume N = 10
col_fun = function(x) {
    # I use this way because `col_fun` will be applied to a vector, so it should be vectorized.
    ifelse(x == -1, "green", ifelse(x == -2, "yellow", col_fun1(x)))
}
```

But for the self-defined color-mapping function, you should add a `breaks` attribute to the function so that the legend can be correctly drawn.

```r
attr(col_fun, "breaks") = c(0, 10)
```

A runnable example is:

```r
m = matrix(sample(-2:12, 100, replace = TRUE), nrow = 10)

col_fun1 = colorRamp2(c(0, 10), c("white", "red")) # assume N = 10
col_fun = function(x) {
    # I use this way because `col_fun` will be applied to a vector, so it should be vectorized.
    ifelse(x == -1, "green", ifelse(x == -2, "yellow", col_fun1(x)))
}

attr(col_fun, "breaks") = c(0, 10)

ht = Heatmap(m, col = col_fun)
draw(ht, heatmap_legend_list = list(Legend(at = c(-2, -1), 
	labels = c("foo", "bar"), 
	legend_gp = gpar(fill = c("green", "yellow")))))
```

![image](https://user-images.githubusercontent.com/449218/88151172-a3e64700-cc02-11ea-802a-aec4f04a4dd4.png)

**Comment by rcalandrelli** [comment]
Thank you very much for the prompt and clear explanation!
