### ISSUE TITLE
Error when combining named heatmap lists

### ISSUE THREAD

**Issue by rbagd** [jokergoo/ComplexHeatmap#56]
I fail to combine lists of heatmaps where each list has a column title appended. This affects the latest Github version as well as the one on BioC 3.3.

Here's a minimal snippet to replicate the issue.

```
library(ComplexHeatmap)
plots <- list()
for (i in 1:4) {
  plots[[i]] <- Heatmap(matrix(rnorm(20*10), 20, 10))
}
g1 <- draw(plots[[1]] + plots[[2]], column_title="Group1")
g2 <- draw(plots[[3]] + plots[[4]], column_title="Group2")
g1 + g2

Error in `[.unit`(gap, seq_len(i - 1)) : 
  index out of bounds ('unit' subsetting)
```

On the other hand, if first element doesn't have a title, e.g. `plots[[1]] + g1`, then the plot works but without the column title.

**Comment by jokergoo** [comment]
Hi, currently the package does not support grouping heatmaps and adding titles for each group separately. The package can only either add title for each single heatmap or add title with taking all heatmaps as a whole.

For your case, I have a not so good solution:

```{r}
plots <- list()
for (i in 1:4) {
  plots[[i]] <- Heatmap(matrix(rnorm(20*10), 20, 10), name = paste0("ht", i), column_title = "foo",
  	column_title_gp = gpar(col = "white"))
}
ht_list <- plots[[1]] + plots[[2]]+ plots[[3]] + plots[[4]]

decorate_column_title("ht1", {
	grid.text("group1", x = unit(1, "npc") + unit(1, "mm"))
})

decorate_column_title("ht3", {
	grid.text("group1", x = unit(1, "npc") + unit(1, "mm"))
})
```

So basically, I use `decorate_column_title()` and add the column title in the middle of the two neighbouring heatmaps. In you case it is easy to calculate the middle point of the two heatmaps because the two heatmap have the same number of columns. But in a more general case (more than two heatmaps and with unequal number of columns), it will be a little bit more complex to get the position of the middle point.

![test](https://cloud.githubusercontent.com/assets/449218/17584680/43ba1f2e-5fb8-11e6-991d-0101616fbd04.png)

**Comment by rbagd** [comment]
@jokergoo , thanks for the work-around and a quick reply. Maybe this could then be tagged as **_Feature/Enhancement_**? I can see a few cases where grouped heatmaps could be of use.
