### ISSUE TITLE
treat column and row annotations consistently

### ISSUE THREAD

**Issue by rmflight** [jokergoo/ComplexHeatmap#6]
As far as I can see, in `1.2.1`, if I want both **row** and **column** annotations, I need to use `top_annotation` (or `bottom_annotation`) and then do `+ rowAnnotation`. For consistency, would it make more sense to have one of either:

```r
Heatmap(...., top_annotation = ..., right_annotation = ....)
```

or 

```r
rowAnnot <- HeatmapAnnotation(...., which = "row")
colAnnot <- HeatmapAnnotation(...., which = "col")
Heatmap(....) + rowAnnot + colAnnot
```

Why bother having the ability to set `which` in `HeatmapAnnotation` if you can't use it directly, and why the different methods to add column and row annotations?

**Comment by jokergoo** [comment]
The reason is column annotations only belong to one single heatmap and row annotations can correspond to all heatmaps, so column annotation should only be set as an argument of a single Heatmap and row annotations can be added to the heatmap list.

Actually there are two shortcut functions `columnAnnotation()` and `rowAnnotation()` which set pre-defined `which` in `HeatmapAnnotation()` and you can use `rowAnnotation(...)` instead of using `HeatmapAnnotation(..., which = "row")`:

```{r}
Heatmap(...) + rowAnnotation(...)
```

**Comment by rmflight** [comment]
OK, that makes sense, I guess. Still seems like an odd behavior when thinking in the context of a single heatmap
