### ISSUE TITLE
pheatmap annotations not matched to columns / rows when clustering is turned off.

### ISSUE THREAD

**Issue by dtm2451** [jokergoo/ComplexHeatmap#610]
Hey joker, sorry to be bearer of bad news again... I've noticed another discrepancy with your pheatmap function. This issue is that reordering of the matrix can lead to unlinked annotations, specifically when clustering is not performed.

dittoSeq offers ordering of columns (samples), based on user input, with clustering off, but currently that breaks the annotation matching. I can extend the reordering to annotations myself, but this is another case where "pheatmap::pheatmap does it"... Would it be possible to extend the annotation matching code to outside of just when clustering is run?

Illustration below:
```
library(ComplexHeatmap)

# Make the matrix
test = matrix(rnorm(200), 20, 10)
test[1:10, seq(1, 10, 2)] = test[1:10, seq(1, 10, 2)] + 3
test[11:20, seq(2, 10, 2)] = test[11:20, seq(2, 10, 2)] + 2
test[15:20, seq(2, 10, 2)] = test[15:20, seq(2, 10, 2)] + 4
colnames(test) = paste("Test", 1:10, sep = "")
rownames(test) = paste("Gene", 1:20, sep = "")

# Build annotations
annotation_col = data.frame(
    CellType = factor(rep(c("CT1", "CT2"), 5)), 
    Time = 1:5
)
rownames(annotation_col) = paste("Test", 1:10, sep = "")

annotation_row = data.frame(
    GeneClass = factor(rep(c("Path1", "Path2", "Path3"), c(10, 4, 6))), 
## ADDED: numeric annot
    Time2 = 1:20
)
rownames(annotation_row) = paste("Gene", 1:20, sep = "")

ann_colors = list(
    Time = c("white", "firebrick"),
    Time2 = c("white", "firebrick"),
    CellType = c(CT1 = "#1B9E77", CT2 = "#D95F02"),
    GeneClass = c(Path1 = "#7570B3", Path2 = "#E7298A", Path3 = "#66A61E")
)

# Make a reordered matrix
test_reordered_cols <- test[,order(test[1,])]
test_reordered_both <- test_reordered_cols[order(test[,1]),]
```

```
# No reordering
ComplexHeatmap::pheatmap(
    test,
    annotation_row = annotation_row, annotation_col = annotation_col,
    cluster_cols = FALSE, cluster_rows = FALSE,
    annotation_colors = ann_colors)
```
![image](https://user-images.githubusercontent.com/38870347/96351269-213d1e80-106f-11eb-9001-ea81e0984a10.png)

```
# Reordered matrix, but clustering OFF: annotations unmatched
ComplexHeatmap::pheatmap(
    test_reordered_both,
    annotation_row = annotation_row, annotation_col = annotation_col,
    cluster_cols = FALSE, cluster_rows = FALSE,
    annotation_colors = ann_colors)
```
![image](https://user-images.githubusercontent.com/38870347/96351340-8264f200-106f-11eb-8e66-d7b348ebde3a.png)

```
# Reordered matrix, but clustering is turned ON: annotations reordered
ComplexHeatmap::pheatmap(
    test_reordered_rows,
    annotation_row = annotation_row, annotation_col = annotation_col,
    # cluster_cols = FALSE, cluster_rows = FALSE,
    annotation_colors = ann_colors)
```
![image](https://user-images.githubusercontent.com/38870347/96351350-8f81e100-106f-11eb-9b0b-ee0cddd197b7.png)

**Comment by jokergoo** [comment]
Hi, for this code:

```r
ComplexHeatmap::pheatmap(
    test_reordered_both,
    annotation_row = annotation_row, annotation_col = annotation_col,
    cluster_cols = FALSE, cluster_rows = FALSE,
    annotation_colors = ann_colors)
```

`annotation_row`/`annotation_col` does not have the same order as `test_reordered_both`, right?

Also following code:

```r
ComplexHeatmap::pheatmap(
    test_reordered_rows,
    annotation_row = annotation_row, annotation_col = annotation_col,
    # cluster_cols = FALSE, cluster_rows = FALSE,
    annotation_colors = ann_colors)
```

gives you the wrong plot because `annotation_row` do not have the same order as `test_reordered_rows`.

I think we should always keep the matrix and annotations the same order, because the annotations will be reordered automatically with the cluster/reordering of the main matrix.

I see in pheatmap package, for example, if row names of the row annotation table are the same as the row names of the matrix, the row annotation is reordered automatically, which means, the row annotation table can be randomly permutated and it will always be adjusted to the same ordering as the main matrix. I am not sure whether that is a good idea. My me, my feeling is you should always keep the inputs consistent. Maybe for `pheatmap()` function, the order of row annotations can be automatically adjusted, but how about other downstream analysis with the same annotation tables and won't do the adjustment? That might be dangerous and might give you wrong results.

Anyway, you need to manually reorder the row annotation and column annotation according to the matrix, such as:

```r
co = order(test[1,])
ro = order(test[,1])

ComplexHeatmap::pheatmap(
    test_reordered_both,
    annotation_row = annotation_row[ro, , drop = FALSE], 
    annotation_col = annotation_col[co, , drop = FALSE],
    cluster_cols = FALSE, cluster_rows = FALSE,
    annotation_colors = ann_colors)
```

![image](https://user-images.githubusercontent.com/449218/96360186-07f1ac00-111b-11eb-814a-0f3e084638cf.png)

What do you think? I can do as how `pheatmap:pheatmap()` does, but I prefer to also print a warning message.

**Comment by jokergoo** [comment]
Now it works as `pheatmap::pheatmap()`, but warnings are printed:

```
> pheatmap(
+     test_reordered_both,
+     annotation_row = annotation_row, annotation_col = annotation_col,
+     cluster_cols = FALSE, cluster_rows = FALSE,
+     annotation_colors = ann_colors)
Warning messages:
1: Column annotation has different order from matrix columns. Adjust the
column annotation based on column names of the matrix. 
2: Row annotation has different order from matrix rows. Adjust the row
annotation based on row names of the matrix.
```

**Comment by dtm2451** [comment]
> annotation_row/annotation_col does not have the same order as test_reordered_both, right?
correct.

I think this is a great way of doing it.  Keeps `pheatmap::`'s output, but ensures that users know what they are working with. I can agree that a user might want to be aware of such a discrepancy. I will ensure that the order of `dittoHeatmap()`'s automatically generated `annotation_col` will match the matrix order to avoid this warning.

**Comment by dtm2451** [comment]
Seems to all be in order.

Together with the ordering code I added to dittoSeq v1.1.13 (soon to be 1.2) and changes you made... `dittoHeatmap()` column annotations plot in proper order for either CompleHeatmap v2.5.6(Bioc) or the Github version.  And there is no warning thrown (expected). They also fall in proper order, but with the expected warning, if I purposefully mis-order the `annotation_col`, while I have your Github version installed.
