### ISSUE TITLE
How to set break on continuous color scale for annotation?

### ISSUE THREAD

**Issue by kin182** [jokergoo/ComplexHeatmap#634]
I have a dataset for the top annotation in which there are only a few samples that have high values; therefore, the color scale is skewed up, which becomes hard to see the differences.

For example, most of the samples of `foo1` have values between 0.2 and 0.5, only a few of them have values up to 1 so the entire annotation looks pale. How to set custom scale to have a break at 0.5, for example?

![image](https://user-images.githubusercontent.com/25874665/98165528-e9b9d900-1e9a-11eb-8457-61d757e40ae1.png)

Apologies if it is a simple question.

Thanks,

Kobe

**Comment by asalt** [comment]
You can fiddle around with the color boundaries. For example: 

`colorRamp2(c(0, 1), c("palegreen", "palegreen4"))`

**Comment by kin182** [comment]
Yes, I have done it but the color change is uniformly increased, leaving most colors palegreen. I am looking for a break beyond 0.5 for example so the changes between 0.2 to 0.5 are more visible.

**Comment by asalt** [comment]
Sounds like you need to transform your data into another space.

**Comment by jokergoo** [comment]
You can always precisely control your color mapping in `colorRamp2()`. On the other hand, as @asalt suggested, or maybe you should apply some transformation on your data to make it more like uniformly distributed (because the colors are linearly interpolated between break values which you set in `colorRamp2()`), such as log-transformation or square-root transformation?

**Comment by kin182** [comment]
Transforming the data works. Thanks!
