### ISSUE TITLE
Can't Replicate Default Clustering Results

### ISSUE THREAD

**Issue by eggerj** [jokergoo/ComplexHeatmap#710]
Hello,

The documentation states that the default clustering method for rows and columns is complete linkage clustering using euclidean distance. However, I do not get the same clustering results when I supply my own dendrograms using those same options (hclust). 

I do get the same results with default clustering from pheatmap. Is there something else going on with the default clustering I am not aware of? How can I replicate the default clustering with my own row/column dendrograms?

```
library(fastcluster)
library(pheatmap)
library(ComplexHeatmap)

# Create random matrix
i <- 8
mat <- matrix(rnorm(i^2), nc = i, dimnames = list(letters[1:i],c(1:i)))

# Cluster rows and columns
dRows <- hclust(dist(mat, method = 'euclidean'), method = 'complete')
dCols <- hclust(dist(t(mat), method = 'euclidean'), method = 'complete')

# Pheatmap with dendrograms
pheatmap(mat,
         cluster_rows = dRows,
         cluster_cols = dCols,
         border_color=NA, 
         width=7, height=7)
```
![pheatmap_dendro](https://user-images.githubusercontent.com/13209340/112058618-08ea9780-8b18-11eb-87c2-b52e720c6622.png)

```
# Pheatmap with autocluster <-- Clustering is the same
pheatmap(mat,
         #cluster_rows = dRows,
         #cluster_cols = dCols,
         border_color=NA, 
         width=7, height=7)

```
![pheatmap_auto](https://user-images.githubusercontent.com/13209340/112058674-1dc72b00-8b18-11eb-96c7-6985f89066ba.png)

```
# ComplexHeatmap with dendrograms
Heatmap(mat,
        cluster_rows = dRows,
        cluster_columns = dCols,
        width = 7, height = 7)
```

![complexheatmap_dendro](https://user-images.githubusercontent.com/13209340/112058751-36374580-8b18-11eb-8655-d2ef69a86db3.png)

```
# ComplexHeatmap with autocluster <-- Clustering is different
Heatmap(mat,
        #cluster_rows = dRows,
        #cluster_columns = dCols,
        width = 7, height = 7)
```
![complexheatmap_auto](https://user-images.githubusercontent.com/13209340/112058824-4cdd9c80-8b18-11eb-8a1a-ca58506ff0fa.png)

Note the slight difference in clustering results between the last two heatmaps plotted with ComplexHeatmap.

Thank you!

**Comment by jokergoo** [comment]
Hi, this is because ComplexHeatmap applies dendrogram reordering by default. In most cases, dendrogram reordering improves the visual effect of the heatmap, i.e., patterns that are more different are more far from each other. As shown in your last heatmap, red blocks locate on the top left and blue blocks locate on the bottom right. They are the two most distinct patterns. 

On the other hand, the dendrogram in the last heatmap actually are "identical" to other dendrograms because you can freely rotate the two branches at any node in the dendrogram while not changing the clustering result.

You can set `row_dend_reoder = FALSE` and `column_dend_reorder = FALES` to turn off dendrogram reordering.

**Comment by eggerj** [comment]
Ok, that makes sense. Great feature! 

Thank you!
