### ISSUE TITLE
subset heatmap

### ISSUE THREAD

**Issue by saisaitian** [jokergoo/ComplexHeatmap#771]
Dear author，I have a question on how to subset heatmap：

for example：
![image](https://user-images.githubusercontent.com/26356557/125427251-18b13240-ff01-4920-9d51-6b6175a72d34.png)

I only want subset the part of heatmap，could you tell me how to get it？
![image](https://user-images.githubusercontent.com/26356557/125427452-7170892e-8469-43f0-8981-8a0669e594db.png)

**Comment by saisaitian** [comment]
I know the means，but I could not retain the color bar and hcluster，I want retain these important information。

![image](https://user-images.githubusercontent.com/26356557/125436383-551cdec0-8f41-4d4f-9b79-6258cb64ffa7.png)

if I use the index， I only get simple heatmap

![image](https://user-images.githubusercontent.com/26356557/125436615-13d39f7e-3ff2-47c3-a141-c8902c61b27b.png)

**Comment by jokergoo** [comment]
The clustering will of course be different because the clustering in the original heatmap is based on the complete matrix.

Actually you can keep the order from the clustering while not drawing it.

You can first set `row_split` and `column_split` to split the dendrograms on the two sides:

```r
ht = Heatmap(mat, row_split = 3, column_split = 3, ...)
ht = draw(ht)
row_order = row_order(ht)
column_order = column_order(ht)
```

`row_order` is a list and the first element corresponds to the first row cluster. Similarly, the first element in `column_order` is the subset of columns in the first column cluster.

```r
subm = mat[row_order[[1]], column_order[[1]]]
```

Now `subm` is reordered and has the same order as in the original heatmap, you can draw it without doing clustering:

```r
Heatmap(subm, ..., cluster_rows = FALSE, cluster_columns = FALSE)
```

**Comment by saisaitian** [comment]
In fact，the original hcluster was lost，If I want retained it，how can I do？

![image](https://user-images.githubusercontent.com/26356557/125442966-97bb7bb8-e496-46de-8657-84a43d328e41.png)

**Comment by saisaitian** [comment]
In addition， when I use column_split parameter，the decorate_column_dend function get an error。If I do not use column_split parameter，it was ok。 Colud you tell me how to fix it？

code were as follows
![image](https://user-images.githubusercontent.com/26356557/125443774-fb4a2c4c-0621-4d38-a365-9b7ed0646415.png)

**Comment by jokergoo** [comment]
I think the code in `decorate_column_dend` is to highlight the branch with which the real aim is to highlight the groups of samples. Now you set `column_split = 4` which already separates the samples into groups. I think it is not needed for using `decorate_column_dend`, right?

The error is from `column_dend(ht)`. Now you set `column_split = 4`, the object returned from `column_dend()` is not a dendrogram anymore, while it is a list of 4 dendrograms.

PS. please do not attach your code as a screenshot. I cannot copy the code from it.
