### ISSUE TITLE
Cairo exports are white or missing when plotting inside a function

### ISSUE THREAD

**Issue by bersbersbers** [jokergoo/ComplexHeatmap#808]
```R
cairo_pdf("working.pdf")
ComplexHeatmap::Heatmap(c(1, 2, 3))
dev.off()

do <- function() {
    cairo_pdf("broken.pdf")
    ComplexHeatmap::Heatmap(c(1, 2, 3))
    dev.off()
}
do()
```

`working.pdf` is looking fine - `broken.pdf` is all white.

With PNG export, `broken.png` is not even written.

```r
png("working.png", type="cairo")
ComplexHeatmap::Heatmap(c(1, 2, 3))
dev.off()

do <- function() {
    png("broken.png", type = "cairo")
    ComplexHeatmap::Heatmap(c(1, 2, 3))
    dev.off()
}
do()
```

![image](https://user-images.githubusercontent.com/12128514/134081984-1b0e0fc5-4103-46cd-b333-76fb16830b30.png)

**Comment by bersbersbers** [comment]
I can repro this on Windows and Linux. I save the above as `bug.R` and run `Rscript bug.R`. I believe the problem is not restricted to Cairo exports, but haven't tested further.

**Comment by jokergoo** [comment]
If heatmaps are drawn inside a function, an R script or a code block, e.g. `for` or `if-else`, you need to explicitely use `draw()` function:

```r
do <- function() {
    png("broken.png", type = "cairo")
    draw(Heatmap(c(1, 2, 3)))
    dev.off()
}
```

The reason is `Heatmap()` is actually a constructor function, while not a plotting function, like in ggplot2. In an interactive environment, directly enter `Heatmap()` actually call the corresponding `print()`/`show()` method and `show,Heatmap-method` is actually the plotting function.

**Comment by bersbersbers** [comment]
Thanks!

- I had previously tried `plot`, but that resulted in 

>   cannot coerce type 'S4' to vector of type 'double'

- `print` gave a white file as well.

- `show` is new to me - working great! And I prefer that over `ComplexHeatmap::draw` because it's generic, and I can use it for other plot types as well.
