### ISSUE TITLE
Reordering dendrogram when columns are split

### ISSUE THREAD

**Issue by jmchan88** [jokergoo/ComplexHeatmap#864]
Related to the question posed in https://github.com/jokergoo/ComplexHeatmap/issues/31, is there a way to reorder the dendrogram using the rotate function in the package dendextend, or any other alternative, in the case of a dendrogram built on split columns (or rows)?

Thank you so much!
Joe

**Comment by jokergoo** [comment]
I think yes since the rotated dendrogram is still a `dendrogram` object. See the following examples:

```r

hc <- hclust(dist(USArrests[c(1, 6, 13, 20, 23), ]), "ave")
dend <- as.dendrogram(hc)
```

There are two heatmaps, the second one I applied column splitting

```r
m = t(USArrests[c(1, 6, 13, 20, 23), ])
Heatmap(m, cluster_columns = dend) +
Heatmap(m, cluster_columns = dend, column_split = 2)
```

![image](https://user-images.githubusercontent.com/449218/152324568-f5945af1-3322-411e-a312-1d1194f8c9af.png)

Next I rotate the branches of the column dendrogram:

```r
library(dendextend)

dend2 = rotate(dend, c(2:5, 1))
Heatmap(m, cluster_columns = dend2) +
Heatmap(m, cluster_columns = dend2, column_split = 2)
```

![image](https://user-images.githubusercontent.com/449218/152324715-2f5e69ae-6b22-4e13-93bc-d0810106f891.png)

**Comment by jmchan88** [comment]
Thanks for the reply! Interesting, what if the split column is in the middle of the other clade?
