### ISSUE TITLE
Add plot outside of ComplexHeatmap package as top annotation

### ISSUE THREAD

**Issue by jeichholz29** [jokergoo/ComplexHeatmap#903]
Hi Zuguang,

Thank you so much for creating this amazing package! I am curious whether there will be additional capabilities or if there are existing functions that would allow me to add ggplot  or base r plots as the top annotation for oncoprints? 

All the Best,
Jordan

**Comment by jokergoo** [comment]
You can first create an empty annotation and later add any type of graphics with `decorate_annotation()`, but you need to take care of the reordering due to clustering.

```r

m = matrix(rnorm(100), 10)

Heatmap(m, top_annotation = HeatmapAnnotation(foo = anno_empty(height = unit(6, "cm"))))

p = ggplot(mtcars,aes(x=wt,y=mpg)) + geom_point()
p = grid.grabExpr(print(p))
decorate_annotation("foo", {
    grid.draw(p)
})
```

<img width="913" alt="image" src="https://user-images.githubusercontent.com/449218/163036861-13474f6e-1a14-49f3-a260-deb64c5694f4.png">

**Comment by ManuelSokolov** [comment]
Hello, Zuguang.

What if jeichholz29 wanted to draw an plot with shared x axis with the heatmap? How could he change the code assuming that wt variable would have the same values of the heatmap?

Thanks.
