### ISSUE TITLE
Ladderize dendrograms

### ISSUE THREAD

**Issue by dariober** [jokergoo/ComplexHeatmap#912]
Hi- This is only a suggestion. I would [ladderize](https://rdrr.io/cran/dendextend/man/ladderize.html) the dendrograms created within `Heatmap`. Ladderizing usually gives better visualization without changing the actual clustering.

I'm probably speaking too early here, but it may be just a matter of wrapping the `dend <- as.dendrogram(hclust(d))` calls into `dendextend::ladderize`. E.g.:

```
dend <- ladderize(as.dendrogram(hclust(dist(mat))))
```

**Comment by jokergoo** [comment]
Thanks for the suggestion! 

I would not put it as a part of ComplexHeatmap because it already has many arguments. On the other hand, it is just a transformation of taking in a dendrogram object and returning a new dendrogram object. The dendrogram can be pre-compuated, ladderized and then assign to `cluster_rows`/`cluster_columns` argument.

```{r}
dend = as.dendrogram(hclust(dist(mat)))
Heatmap(m, cluster_rows = dend)
```
